import {escape,slugify,markdown,validatePost,validatePosts,readTime,CATEGORIES} from '/assets/blog-engine.mjs';
import {GitHubPublisher} from '/assets/github-publisher.mjs';
const $=s=>document.querySelector(s), fields={title:$('#post-title'),slug:$('#post-slug'),excerpt:$('#post-excerpt'),category:$('#post-category'),body:$('#post-body'),coverAlt:$('#cover-alt')};
let client=null,snapshot=null,draft=null,saveTimer=null,busy=false,slugTouched=false;
const status=(message,error=false)=>{const el=$('#global-status');el.textContent=message;el.classList.toggle('error',error);if(error)el.scrollIntoView({behavior:'smooth',block:'nearest'});};
function task(fn){return async event=>{try{await fn(event);}catch(e){status(e.message||'Er ging iets mis. Probeer opnieuw.',true);}};}
async function exclusive(fn){if(busy)return;busy=true;const active=document.activeElement;const controls=[...document.querySelectorAll('input,textarea,select,button')],before=controls.map(e=>e.disabled);controls.forEach(e=>e.disabled=true);try{return await fn();}finally{controls.forEach((e,i)=>e.disabled=before[i]);busy=false;if(active?.isConnected)active.focus({preventScroll:true});}}
const dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open('smits-digital-blog',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Conceptopslag is niet beschikbaar. Exporteer je concept om het te bewaren.'));});
// Handle unavailable storage immediately, but keep writing/export functional.
dbPromise.catch(()=>{});
async function dbAction(method,value){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',method==='getAll'?'readonly':'readwrite'),store=tx.objectStore('drafts');const req=method==='getAll'?store.getAll():store[method](value);tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(Error('Concept kon niet worden opgeslagen. Exporteer het als back-up.'));tx.onabort=tx.onerror;});}
function collect(){if(!draft)return null;for(const [key,el]of Object.entries(fields))draft.post[key]=el.value;return structuredClone(draft);}
async function saveDraft(){clearTimeout(saveTimer);saveTimer=null;const value=collect();if(!value)return;value.savedAt=new Date().toISOString();await dbAction('put',value);if(draft?.id===value.id)$('#save-state').textContent='Concept opgeslagen op dit apparaat';await renderDrafts();}
function scheduleSave(){if(!draft)return;$('#save-state').textContent='Concept wordt bewaard…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft().catch(e=>{$('#save-state').textContent=e.message;}),650);}
function changed(){collect();updateHints();scheduleSave();}
function setImage(img,path){const asset=draft?.images.find(x=>'/'+x.path===path);img.src=asset?`data:image/webp;base64,${asset.base64}`:path;}
function updateHints(){const p=collect();if(!p)return;$('#excerpt-count').textContent=`${p.post.excerpt.length}/200`;const words=p.post.body.trim()?p.post.body.trim().split(/\s+/).length:0;$('#word-count').textContent=`${words} woorden · ${readTime(p.post)} min lezen`;$('#seo-title').textContent=(p.post.title||'Titel van jouw artikel')+' | Smits Digital';$('#seo-description').textContent=p.post.excerpt||'Je samenvatting verschijnt hier.';$('#cover-preview').hidden=!p.post.cover;if(p.post.cover)setImage($('#cover-preview'),p.post.cover);}
async function renderDrafts(){let list;try{list=await dbAction('getAll');}catch{return;}$('#draft-list').replaceChildren();list.sort((a,b)=>(b.savedAt||'').localeCompare(a.savedAt||''));for(const d of list){const b=document.createElement('button');b.className='post-select';b.type='button';b.textContent=d.post.title||'Naamloos concept';const sub=document.createElement('span');sub.textContent=d.originalUpdatedAt?'Wijziging van gepubliceerd artikel':'Nog niet gepubliceerd';b.append(sub);b.addEventListener('click',task(async()=>{await saveCurrent();openDraft(d);}));$('#draft-list').append(b);}if(!list.length)$('#draft-list').textContent='Nog geen concepten.';}
function renderPosts(){const list=$('#post-list');list.replaceChildren();for(const p of [...snapshot.posts].sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt))){const b=document.createElement('button');b.type='button';b.className='post-select';b.textContent=p.title;const s=document.createElement('span');s.textContent='Gepubliceerd · '+new Date(p.publishedAt).toLocaleDateString('nl-NL');b.append(s);b.addEventListener('click',task(async()=>{await saveCurrent();const all=await dbAction('getAll').catch(()=>[]);const local=all.find(d=>d.originalUpdatedAt&&d.post.slug===p.slug);if(local&&confirm('Er is een lokaal concept voor dit artikel. Wil je daarmee verder?'))openDraft(local);else openDraft({id:crypto.randomUUID(),post:structuredClone(p),originalUpdatedAt:p.updatedAt,images:[]});}));list.append(b);}if(!snapshot.posts.length)list.textContent='Nog geen publicaties.';}
async function saveCurrent(){if(draft)await saveDraft().catch(e=>{status(e.message,true);});}
function openDraft(d){clearTimeout(saveTimer);saveTimer=null;draft=structuredClone(d);slugTouched=!!draft.post.slug;for(const [key,el]of Object.entries(fields))el.value=draft.post[key]||'';fields.slug.readOnly=!!draft.originalUpdatedAt;$('#editor-state').textContent=draft.originalUpdatedAt?'Gepubliceerd artikel bewerken':'Nieuw concept';$('#save-state').textContent='';$('#editor').hidden=false;$('#editor-empty').hidden=true;$('#delete-post').hidden=!draft.originalUpdatedAt;$('#publish').textContent=draft.originalUpdatedAt?'Wijzigingen publiceren ↗':'Publiceren ↗';$('#cover-upload').value='';$('#body-upload').value='';updateHints();}
function clearEditor(){clearTimeout(saveTimer);saveTimer=null;draft=null;$('#editor').hidden=true;$('#editor-empty').hidden=false;}
function blank(){const now=new Date().toISOString();return{id:crypto.randomUUID(),post:{title:'',slug:'',excerpt:'',category:CATEGORIES[0],body:'',cover:'',coverAlt:'',publishedAt:now,updatedAt:now},originalUpdatedAt:null,images:[]};}
for(const el of Object.values(fields))el.addEventListener('input',()=>{if(el===fields.title&&!slugTouched&&!draft?.originalUpdatedAt)fields.slug.value=slugify(el.value);if(el===fields.slug)slugTouched=true;changed();});
$('#login-form').addEventListener('submit',task(async e=>{e.preventDefault();await exclusive(async()=>{status('Verbinden met GitHub…');const token=$('#token').value.trim();if(!token)throw Error('Vul je toegangstoken in.');const response=await fetch('/admin/config.json',{cache:'no-store'});if(!response.ok)throw Error('Configuratie niet gevonden. Upload de volledige zip.');const config=await response.json();const candidate=new GitHubPublisher(config,token);try{const loaded=await candidate.snapshot();client=candidate;snapshot=loaded;}catch(error){candidate.disconnect();throw error;}finally{$('#token').value='';}$('#login-panel').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#repo-label').textContent=`${config.owner}/${config.repo} · ${config.branch}`;renderPosts();await renderDrafts();status('Verbonden. Kies een artikel of begin met een nieuw concept.');});}));
$('#logout').addEventListener('click',task(async()=>{await saveCurrent();client?.disconnect();client=null;snapshot=null;clearEditor();$('#workspace').hidden=true;$('#login-panel').hidden=false;$('#logout').hidden=true;status('Uitgelogd. Lokale concepten blijven op dit apparaat staan.');}));
$('#new-post').addEventListener('click',task(async()=>{await saveCurrent();openDraft(blank());fields.title.focus();}));
$('#refresh').addEventListener('click',task(async()=>{await exclusive(async()=>{await saveCurrent();snapshot=await client.snapshot();renderPosts();status('Publicaties zijn opnieuw geladen. Je huidige concept is behouden.');});}));
function insert(before,after='',placeholder='tekst'){const el=fields.body,start=el.selectionStart,end=el.selectionEnd,selected=el.value.slice(start,end)||placeholder;el.setRangeText(before+selected+after,start,end,'end');el.focus();changed();}
const formats={heading:['\n\n## ','\n\n','Tussenkop'],subheading:['\n\n### ','\n\n','Subkop'],bold:['**','**','belangrijke tekst'],list:['\n- ','\n','Eerste punt'],quote:['\n\n> ','\n\n','Citaat']};
document.querySelectorAll('[data-format]').forEach(b=>b.addEventListener('click',()=>insert(...formats[b.dataset.format])));
let savedSelection=[0,0];$('#insert-link').addEventListener('click',()=>{savedSelection=[fields.body.selectionStart,fields.body.selectionEnd];$('#link-text').value=fields.body.value.slice(...savedSelection);$('#link-url').value='';$('#link-dialog').showModal();});
$('#cancel-link').addEventListener('click',()=>$('#link-dialog').close());
$('#link-form').addEventListener('submit',task(async e=>{e.preventDefault();const {safeURL}=await import('/assets/blog-engine.mjs');const url=safeURL($('#link-url').value),label=$('#link-text').value.replace(/[\[\]\n]/g,'');if(!url||/[()]/.test(url))throw Error('Gebruik een geldig https://-webadres of een intern pad zonder haakjes.');fields.body.setRangeText(`[${label}](${url})`,...savedSelection,'end');changed();$('#link-dialog').close();}));
async function optimizedImage(file){
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('Kies een JPG-, PNG- of WebP-foto van maximaal 15 MB.');
  const url=URL.createObjectURL(file),img=new Image();
  try{img.src=url;await img.decode();if(img.naturalWidth*img.naturalHeight>40000000)throw Error('Deze foto heeft te veel pixels. Verklein hem eerst tot maximaal 40 megapixel.');const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(img.naturalWidth*scale);canvas.height=Math.round(img.naturalHeight*scale);const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/webp',.84);if(!data.startsWith('data:image/webp;'))throw Error('Deze browser kan geen WebP-foto’s maken. Gebruik een recente Chrome, Edge, Firefox of Safari.');const base64=data.split(',')[1];if(base64.length>3000000)throw Error('Deze foto blijft te groot. Verklein hem en probeer opnieuw.');return{path:`assets/blog/${slugify(file.name.replace(/\.[^.]+$/,''))||'foto'}-${crypto.randomUUID()}.webp`,base64};}finally{URL.revokeObjectURL(url);}
}
async function upload(files,cover=false){if(!draft)return;if(files.length+draft.images.length>20)throw Error('Gebruik maximaal 20 nieuwe foto’s per concept.');await exclusive(async()=>{status('Foto’s optimaliseren…');for(const file of files){const asset=await optimizedImage(file);draft.images.push(asset);if(cover){draft.post.cover='/'+asset.path;}else{const name=file.name.replace(/\.[^.]+$/,'').replace(/[\[\]\n]/g,'');fields.body.setRangeText(`\n\n![${name}](/${asset.path})\n\n`,fields.body.selectionStart,fields.body.selectionEnd,'end');changed();}}updateHints();await saveDraft();status(cover?'Omslagfoto toegevoegd. Vul ook een beschrijving in.':'Foto’s toegevoegd. Pas de tekst tussen [ ] aan om de afbeeldingen te beschrijven.');});}
$('#cover-upload').addEventListener('change',task(e=>upload([...e.target.files].slice(0,1),true)));
$('#insert-image').addEventListener('click',()=>$('#body-upload').click());$('#body-upload').addEventListener('change',task(async e=>{await upload([...e.target.files]);e.target.value='';}));
$('#preview-button').addEventListener('click',()=>{const {post:p}=collect(),body=markdown(p.body).html;$('#preview-content').innerHTML=`<span class="kicker">${escape(p.category)} · ${readTime(p)} min lezen</span><h1>${escape(p.title||'Titel van jouw artikel')}</h1><p class="article-lead">${escape(p.excerpt)}</p>${p.cover?`<img src="${escape(p.cover)}" alt="${escape(p.coverAlt)}">`:''}<div class="prose">${body}</div>`;$('#preview-content').querySelectorAll('img').forEach(img=>setImage(img,img.getAttribute('src')));$('#preview-dialog').showModal();});$('#close-preview').addEventListener('click',()=>$('#preview-dialog').close());
$('#editor-form').addEventListener('submit',task(async e=>{e.preventDefault();collect();const errors=validatePost(draft.post);if(errors.length)throw Error(errors.join(' '));const p=structuredClone(draft.post),existing=snapshot.posts.find(x=>x.slug===p.slug);if(!draft.originalUpdatedAt&&existing)throw Error('Deze artikel-URL bestaat al. Kies een andere URL.');if(draft.originalUpdatedAt&&(!existing||existing.updatedAt!==draft.originalUpdatedAt))throw Error('Dit artikel is sinds jouw concept gewijzigd of verwijderd. Exporteer je concept en open de actuele publicatie voordat je de wijzigingen overneemt.');if(!confirm('Dit artikel wordt openbaar opgeslagen in GitHub en daarna door je websitehost gepubliceerd. Doorgaan?'))return;await exclusive(async()=>{status('Artikel en foto’s opslaan in GitHub…');await saveDraft().catch(()=>{});p.updatedAt=new Date().toISOString();if(!draft.originalUpdatedAt)p.publishedAt=p.updatedAt;const posts=[...snapshot.posts.filter(x=>x.slug!==p.slug),p];const images=draft.images.filter(i=>p.cover==='/'+i.path||p.body.includes('/'+i.path));snapshot=await client.publish(snapshot,posts,images,`Blog: ${p.title}`);const oldId=draft.id,uploadedImages=draft.images;await dbAction('delete',oldId).catch(()=>{});openDraft({id:crypto.randomUUID(),post:p,originalUpdatedAt:p.updatedAt,images:uploadedImages});renderPosts();await renderDrafts();status(`Opgeslagen in GitHub. Je host moet de wijziging nog verwerken; controleer daarna /blog/${p.slug}/ op je website.`);});}));
$('#delete-post').addEventListener('click',task(async()=>{if(!draft?.originalUpdatedAt)return;const slug=draft.post.slug,existing=snapshot.posts.find(p=>p.slug===slug);if(!existing||existing.updatedAt!==draft.originalUpdatedAt)throw Error('De publicatie is gewijzigd. Vernieuw de lijst en open het actuele artikel.');if(!confirm('Publicatie verwijderen? De artikelpagina verdwijnt van je website. De inhoud blijft in de GitHub-geschiedenis en eventuele lokale concepten staan.'))return;await exclusive(async()=>{status('Publicatie verwijderen…');snapshot=await client.publish(snapshot,snapshot.posts.filter(p=>p.slug!==slug),[],`Blog verwijderd: ${slug}`);await dbAction('delete',draft.id).catch(()=>{});clearEditor();renderPosts();await renderDrafts();status('Publicatie uit GitHub verwijderd. Je host verwerkt de wijziging.');});}));
$('#discard-draft').addEventListener('click',task(async()=>{if(!draft||!confirm('Dit lokale concept wissen? Een bestaande publicatie blijft behouden.'))return;clearTimeout(saveTimer);await dbAction('delete',draft.id);clearEditor();await renderDrafts();status('Lokaal concept gewist.');}));
function download(value,filename){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-draft').addEventListener('click',()=>{if(draft)download({format:'smits-digital-draft-v1',draft:collect()},`${draft.post.slug||'blog-concept'}.json`);});
$('#import-draft').addEventListener('click',()=>$('#draft-file').click());
function cleanImport(value){
 if(value.format!=='smits-digital-draft-v1'||!value.draft?.post||!Array.isArray(value.draft.images))throw Error('Dit is geen Smits Digital-concept.');
 const d=value.draft,p=d.post;if(d.images.length>20)throw Error('Te veel afbeeldingen in dit concept.');
 const post={};for(const key of ['title','slug','excerpt','category','body','cover','coverAlt','publishedAt','updatedAt']){if(typeof p[key]!=='string'||p[key].length>(key==='body'?100000:1000))throw Error('Ongeldig conceptveld.');post[key]=p[key];}
 if(!CATEGORIES.includes(post.category))throw Error('Onbekende categorie.');if(post.cover&&!/^\/assets\/blog\/[\w.-]+\.(webp|png|jpg|jpeg)$/.test(post.cover))throw Error('Ongeldige omslagfoto.');
 const images=d.images.map(i=>{if(!/^assets\/blog\/[\w-]+\.webp$/.test(i.path)||typeof i.base64!=='string'||i.base64.length>3000000||!/^[A-Za-z0-9+/]*={0,2}$/.test(i.base64))throw Error('Ongeldige conceptafbeelding.');const binary=atob(i.base64.slice(0,24));if(!binary.startsWith('RIFF')||binary.slice(8,12)!=='WEBP')throw Error('Conceptafbeelding is geen WebP-foto.');return{path:i.path,base64:i.base64};});
 return {id:crypto.randomUUID(),post,originalUpdatedAt:typeof d.originalUpdatedAt==='string'?d.originalUpdatedAt:null,images};
}
$('#draft-file').addEventListener('change',task(async e=>{const f=e.target.files[0];if(!f)return;if(f.size>45*1024*1024)throw Error('Dit conceptbestand is te groot (maximaal 45 MB).');const imported=cleanImport(JSON.parse(await f.text()));await saveCurrent();openDraft(imported);await saveDraft();e.target.value='';status('Concept geïmporteerd. Controleer de inhoud en het voorbeeld voordat je publiceert.');}));
addEventListener('beforeunload',e=>{if(saveTimer&&draft){e.preventDefault();e.returnValue='';}});
// Lock the editor after 30 minutes without interaction. Drafts stay local; tokens never persist.
let lastActivity=Date.now();for(const type of ['pointerdown','keydown'])addEventListener(type,()=>{lastActivity=Date.now();},{passive:true});setInterval(()=>{if(client&&!busy&&Date.now()-lastActivity>30*60*1000)$('#logout').click();},60000);
